### ISSUE TITLE
Can't compare functions in Postgres 11

### ISSUE THREAD

**Issue by ErunamoJAZZ** [ambrogio-dev/pg-compare#15]
Hi

I was testing this with a Postgres 11 and I got this error:
```
loading functions error { error: no existe la columna p.proisagg
    at Connection.parseE (/usr/lib/node_modules/pg-compare/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/usr/lib/node_modules/pg-compare/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/usr/lib/node_modules/pg-compare/node_modules/pg/lib/connection.js:120:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  name: 'error',
  length: 175,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Probablemente quiera hacer referencia a la columna «p.prolang».',
  position: '324',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3294',
  routine: 'errorMissingColumn' }
load done
/*** Comparing terminated with errors ***/
```
This error make reference to https://github.com/ambrogio-dev/pg-compare/blob/264278562b394a73c2c1a40317904765cda1d195/lib/Schema.js#L440

Googling it, I found now postgres use a column named `prokind` instead, like you can see in https://github.com/jOOQ/jOOQ/issues/7785

**Comment by alemar11** [comment]
@timdinhdotcom could you create a pull request?

**Comment by RobinQ124274** [comment]
Made a pull request for this (see #16)
