### ISSUE TITLE
PG 12 Error

### ISSUE THREAD

**Issue by netvoip** [ambrogio-dev/pg-compare#18]
I'm running compare between two postgres 12.1 installations and get following error.
Please update code for compatibility. 

``loading columns public.users error: column f.adsrc does not exist
    at Connection.parseE (/usr/lib/node_modules/pg-compare/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/usr/lib/node_modules/pg-compare/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/usr/lib/node_modules/pg-compare/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) {
  name: 'error',
  length: 106,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '159',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3359',
  routine: 'errorMissingColumn'
``

**Comment by avinashvallarapu** [comment]
I get the same error too
